// <auto-generated />
using DemoApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Infrastructure.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20220509205329_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("DemoApp.Infrastructure.Products.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GeForce RTX 3080",
                            Price = 9449m
                        },
                        new
                        {
                            Id = 2,
                            Name = "980 PRO PCle 4.0 NVMe",
                            Price = 2239m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intel Core i9-10900K",
                            Price = 5490m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fractal DesignDefine R5",
                            Price = 1396m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kingston Fury Beast DDR5",
                            Price = 2645m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
