name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
jobs:
  deploy-to-development:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'development' }}
    environment: 
      name: development
      url: https://emyklebost.github.io/DemoApp/dev/
    steps:
      - name: info
        # Trick for debugging secret: https://www.codementor.io/@zellliew/how-to-debug-a-github-actions-secret-1gbec77cro
        run: echo ${{secrets.MY_EXAMPLE_SECRET }} | sed 's/./& /g'
  deploy-to-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'production' }}
    environment: 
      name: production
      url: https://emyklebost.github.io/DemoApp/prod/
    steps:
      - name: info
        run: echo ${{secrets.MY_EXAMPLE_SECRET }} | sed 's/./& /g'    