name: Package Docker image

on:
  release:
    types: [published]
permissions:
    packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/emyklebost/demo-app:${{ github.sha }},ghcr.io/emyklebost/demo-app:${{ github.event.release.tag_name }}